from . import hr_employee
from . import hr_contract
from . import hr_commission_payslip
from . import hr_commission_payslip_input
from . import hr_commission_payslip_skill
from . import hr_commission_payslip_goal
from . import hr_commission_payslip_line
from . import hr_commission_payslip_worked_days
from . import hr_payslip_run
